<?php 

return [
    [
        'name' => 'LVL 1',
        'capital' => '10000',
        'welcome_bonus' => '1500',
        'daily_tasks' => 2,
        'profit_per_task' => 250,
        'is_automated' => false,
    ],
    [
        'name' => 'LVL 2',
        'capital' => '40000',
        'welcome_bonus' => '3000',
        'daily_tasks' => 5,
        'profit_per_task' => 320,
        'is_automated' => false,
    ],
    [
        'name' => 'LVL 3',
        'capital' => '110000',
        'welcome_bonus' => '6000',
        'daily_tasks' => 10,
        'profit_per_task' => 420,
        'is_automated' => false,
    ],
    [
        'name' => 'LVL 4',
        'capital' => '300000',
        'welcome_bonus' => '15000',
        'daily_tasks' => 15,
        'profit_per_task' => 760,
        'is_automated' => true,
    ],
    [
        'name' => 'LVL 5',
        'capital' => '700000',
        'welcome_bonus' => '50000',
        'daily_tasks' => 20,
        'profit_per_task' => 1250,
        'is_automated' => true,
    ],
    [
        'name' => 'LVL 6',
        'capital' => '1200000',
        'welcome_bonus' => '70000',
        'daily_tasks' => 25,
        'profit_per_task' => 1800,
        'is_automated' => true,
    ],
    [
        'name' => 'LVL 7',
        'capital' => '3000000',
        'welcome_bonus' => '100000',
        'daily_tasks' => 40,
        'profit_per_task' => 2750,
        'is_automated' => true,
    ],
    [
        'name' => 'LVL 8',
        'capital' => '6000000',
        'welcome_bonus' => '150000',
        'daily_tasks' => 60,
        'profit_per_task' => 3900,
        'is_automated' => true,
    ],
    [
        'name' => 'LVL 9',
        'capital' => '9000000',
        'welcome_bonus' => '300000',
        'daily_tasks' => 60,
        'profit_per_task' => 6000,
        'is_automated' => true,
    ],
];